using DiGi.Core;
using DiGi.Geometry.Core.Interfaces;
using DiGi.Geometry.Spatial.Interfaces;
using System.Collections.Generic;

namespace DiGi.Geometry.Spatial.Classes
{
    /// <summary>
    /// Provides a solver to find an internal point within a 3D polygonal face by utilizing a 2D planar projection.
    /// </summary>
    /// <summary>
    /// Initializes a new instance of the <see cref="PolygonalFace3DInternalPointSolver"/> class.
    /// </summary>
    /// <param name="tolerance">The <double> tolerance used for distance calculations.</param>
    /// <summary>
    /// Initializes a new instance of the <see cref="PolygonalFace3DInternalPointSolver"/> class.
    /// </summary>
    /// <param name="maxCount">The <int> maximum count of points to evaluate.</param>
    /// <param name="tolerance">The <double> tolerance used for distance calculations.</param>
    /// <summary>
    /// Gets the resulting <Point3D> internal point calculated by the solver.
    /// </summary>
    /// <returns>The calculated <Point3D> if successful; otherwise, null.</returns>
    public class PolygonalFace3DInternalPointSolver : IInternalPointSolver<IPolygonalFace3D, Point3D>
    {
        private Plane? plane;

        private readonly Planar.Classes.PolygonalFace2DInternalPointSolver polygonalFace2DInternalPointSolver;

        /// <summary>
        /// Initializes a new instance of the <see cref="PolygonalFace3DInternalPointSolver"/> class.
        /// </summary>
        /// <param name="tolerance">The <see cref="double"/> tolerance value used for internal point calculations.</param>
        public PolygonalFace3DInternalPointSolver(double tolerance = DiGi.Core.Constants.Tolerance.Distance)
        {
            polygonalFace2DInternalPointSolver = new Planar.Classes.PolygonalFace2DInternalPointSolver(tolerance);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="PolygonalFace3DInternalPointSolver"/> class.
        /// </summary>
        /// <param name="maxCount">The maximum number of internal points to be calculated as an <see cref="int"/>.</param>
        /// <param name="tolerance">The distance tolerance used for calculations as a <see cref="double"/>.</param>
        public PolygonalFace3DInternalPointSolver(int maxCount, double tolerance = DiGi.Core.Constants.Tolerance.Distance)
        {
            polygonalFace2DInternalPointSolver = new Planar.Classes.PolygonalFace2DInternalPointSolver(maxCount, tolerance);
        }

        /// <summary>
        /// Gets the calculated internal point as a <see cref="Point3D"/>.
        /// </summary>
        /// <value>The converted <see cref="Point3D"/> result from the internal point solver, or null if no output is available.</value>
        public Point3D? Ouput
        {
            get
            {
                return plane.Convert(polygonalFace2DInternalPointSolver.Output);
            }
        }

        /// <summary>
        /// Gets the list of <Point3D> outputs generated by the internal point solver, converted to the plane coordinates and filtered for null values.
        /// </summary>
        public List<Point3D>? Outputs
        {
            get
            {
                return polygonalFace2DInternalPointSolver.Outputs?.ConvertAll(plane.Convert).FilterNulls();
            }
        }

        /// <summary>
        /// Gets or sets the maximum count for the polygonal face 2D internal point solver.
        /// </summary>
        /// <value>An <see cref="int"/> representing the maximum count.</value>
        public int MaxCount
        {
            get
            {
                return polygonalFace2DInternalPointSolver.MaxCount;
            }

            set
            {
                polygonalFace2DInternalPointSolver.MaxCount = value;
            }
        }

        /// <summary>
        /// Gets or sets the <see cref="IPolygonalFace3D"/> input for the polygonal face internal point solver.
        /// </summary>
        public IPolygonalFace3D? Input
        {
            set
            {
                plane = value?.Plane;
                polygonalFace2DInternalPointSolver.Input = value?.Geometry2D;
            }
        }

        /// <summary>
        /// Solves for the internal point of the polygonal face 2D.
        /// </summary>
        /// <returns>A <see cref="bool"/> value indicating whether the operation was successful.</returns>
        public bool Solve()
        {
            if (polygonalFace2DInternalPointSolver is null || plane is null)
            {
                return false;
            }

            return polygonalFace2DInternalPointSolver.Solve();
        }
    }
}